[tool.poetry]
name = "homework5"
version = "0.1.0"
description = "Uvicon base"
authors = ["Bashiru Muyideen"]

[tool.poetry.dependencies]
python = ">=3.12"
fastapi = ">=0.120.0"
ipykernel = ">=7.1.0"
pydantic = ">=2.12.3"
requests = ">=2.32.5"
scikit-learn = "==1.6.1"
uvicorn = ">=0.38.0"